SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Models/SachViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace EBook.Models
{

    public class SachViewModel
    {
        public int Id { get; set; }
        public String TuaSach { get; set; }
        public String HinhMinhHoa { get; set; }
        public HttpPostedFileBase ImgFile { get; set; }
        public String Noidung { get; set; }
        public int LoaiID { get; set; }
        public String TenTheLoai { get; set; }
        public List<LoaiSachModel> DanhMuc { get; set; }
    }
}

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EBook.Models;


namespace EBook.Controllers
{
    public class SachController : Controller
    {
        private EBookDB db = new EBookDB();

        // GET: Sach
        public ActionResult Index()
        {
            return View(db.Database.SqlQuery<SachViewModel>("LietKeSach").ToList());
        }

        // GET: Sach/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SachModel sachModel = db.Sach.Find(id);
            if (sachModel == null)
            {
                return HttpNotFound();
            }
            return View(sachModel);
        }

        // GET: Sach/Create
        public ActionResult Create()
        {
            List<LoaiSachModel> loaisach = db.LoaiSach.ToList<LoaiSachModel>();
            SachViewModel model = new SachViewModel();
            model.DanhMuc = loaisach;
            return View(model);
        }

        // POST: Sach/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TuaSach,ImgFile,Noidung,LoaiID")] SachViewModel sachModel)
        {
            SachModel sach = new Models.SachModel();
            sach.LoaiID = sachModel.LoaiID;
            sach.TuaSach = sachModel.TuaSach;
            sach.Noidung = sachModel.Noidung;
            if (ModelState.IsValid)
            {
                db.Sach.Add(sach);
                db.SaveChanges();
                if (sachModel.ImgFile != null)
                    sachModel.ImgFile.SaveAs(Server.MapPath("/images") + "/" + sach.Id + ".jpg");
                return RedirectToAction("Index");
            }
            sachModel.DanhMuc = db.LoaiSach.ToList<LoaiSachModel>();
            return View(sachModel);
        }

        // GET: Sach/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SachModel sach = db.Sach.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            SachViewModel sachModel = new SachViewModel();
            sachModel.Id = sach.Id;
            sachModel.TuaSach = sach.TuaSach;
            sachModel.HinhMinhHoa = sach.HinhMinhHoa;
            sachModel.Noidung = sach.Noidung;
            sachModel.LoaiID = sach.LoaiID;
            sachModel.DanhMuc = db.LoaiSach.ToList<LoaiSachModel>();
            return View(sachModel);
        }

        // POST: Sach/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TuaSach,ImgFile,HinhMinhHoa,Noidung,LoaiID")] SachViewModel sachModel)
        {
            SachModel sach = new Models.SachModel();
            sach.Id = sachModel.Id;
            sach.TuaSach = sachModel.TuaSach;
            sach.HinhMinhHoa = sachModel.HinhMinhHoa;
            sach.Noidung = sachModel.Noidung;
            sach.LoaiID = sachModel.LoaiID;
            if (ModelState.IsValid)
            {
                db.Entry(sach).State = EntityState.Modified;
                db.SaveChanges();
                if (sachModel.ImgFile != null)
                    sachModel.ImgFile.SaveAs(Server.MapPath("/images") + "/" + sach.Id + ".jpg");
                return RedirectToAction("Index");
            }
            sachModel.DanhMuc = db.LoaiSach.ToList<LoaiSachModel>();
            return View(sachModel);
        }

        // GET: Sach/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SachModel sachModel = db.Sach.Find(id);
            if (sachModel == null)
            {
                return HttpNotFound();
            }
            return View(sachModel);
        }

        // POST: Sach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SachModel sachModel = db.Sach.Find(id);
            db.Sach.Remove(sachModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Views/Sach/Create.cshtml
@using EBook.Models
@model EBook.Models.SachViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Sach", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SachModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TuaSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuaSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TuaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImgFile, new { type = "file",  @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImgFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Noidung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Noidung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Noidung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoaiID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LoaiID, new SelectList(Model.DanhMuc,"LoaiID", "TenTheLoai", -1), "Chọn Thể Loại", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoaiID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Views/Sach/Delete.cshtml
@model EBook.Models.SachModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SachModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TuaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TuaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhMinhHoa)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.HinhMinhHoa)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Noidung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Views/Sach/Details.cshtml
@model EBook.Models.SachModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SachModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TuaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TuaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhMinhHoa)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.HinhMinhHoa)" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Noidung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Views/Sach/Edit.cshtml
@using EBook.Models
@model EBook.Models.SachViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Sach", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SachModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TuaSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TuaSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TuaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImgFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImgFile, new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ImgFile, "", new { @class = "text-danger" })
                @Html.TextBoxFor(model => model.HinhMinhHoa, new { type = "hidden", @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Noidung, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Noidung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Noidung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoaiID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LoaiID, new SelectList(Model.DanhMuc, "LoaiID", "TenTheLoai", -1), "Chọn Thể Loại", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoaiID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SE104 - Nhập môn Công nghệ phần mềm/Thực hành/Xây dựng ứng dụng/Xây dựng ứng dụng WebForm/EBook/EBook/Views/Sach/Index.cshtml
@model IEnumerable<EBook.Models.SachViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TuaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhMinhHoa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Noidung)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenTheLoai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TuaSach)
        </td>
        <td>
            <img src="@Html.DisplayFor(modelItem => item.HinhMinhHoa)" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Noidung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenTheLoai)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>